### ISSUE TITLE
Starting game error

### ISSUE THREAD

**Issue by kingrun** [kirkjerk/joking-at-a-distance#5]
I am trying to self host this. While deploying it on a test php instance I am able to set the username and get a room code . But when I press begin game it shows a 500 http error at the top and nothing happens. Additional people can join with the room code but the game cannot begin. Error in log as follows 

`[Fri May 14 15:56:22 2021] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function startRound(), 1 passed in /var/www/html/arcade/joking-at-a-distance/server/startGame.php on line 24 and exactly 2 expected in /var/www/html/arcade/joking-at-a-distance/server/utils.php:13
Stack trace:
#0 /var/www/html/arcade/joking-at-a-distance/server/startGame.php(24): startRound(Array)
#1 /var/www/html/arcade/joking-at-a-distance/server/utils.php(133): startGameIfCreator(Array)
#2 /var/www/html/arcade/joking-at-a-distance/server/startGame.php(28): updateGame(7090, 'startGameIfCrea...')
#3 {main}
  thrown in /var/www/html/arcade/joking-at-a-distance/server/utils.php on line 13
[Fri May 14 15:56:22 2021] 192.168.0.169:55444 [500]: /server/startGame.php - Uncaught ArgumentCountError: Too few arguments to function startRound(), 1 passed in /var/www/html/arcade/joking-at-a-distance/server/startGame.php on line 24 and exactly 2 expected in /var/www/html/arcade/joking-at-a-distance/server/utils.php:13
Stack trace:
#0 /var/www/html/arcade/joking-at-a-distance/server/startGame.php(24): startRound(Array)
#1 /var/www/html/arcade/joking-at-a-distance/server/utils.php(133): startGameIfCreator(Array)
#2 /var/www/html/arcade/joking-at-a-distance/server/startGame.php(28): updateGame(7090, 'startGameIfCrea...')
#3 {main}
  thrown in /var/www/html/arcade/joking-at-a-distance/server/utils.php on line 13
`

The git is cloned and I have yet to change anything. I see that it expects more arguments for the startRound function but I dont really understand what it is expecting

**Comment by kirkjerk** [comment]
Fixed it, I think. I need to figure out how to run PHP in a stricter mode so I see the issues on my server...
